const tableroInicial = {
    casillas: [[{valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}], 
    [{valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}], 
    [{valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}], 
    [{valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}], 
    [{valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightblue"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}, {valor: null, color: "lightgreen"}], 
    [{valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}], 
    [{valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}], 
    [{valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}], 
    [{valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}], 
    [{valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "lemonchiffon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}, {valor: null, color: "salmon"}]],
    valores: [null, "1", "2", "3", "4", "X"]
};

export default tableroInicial;
